### ISSUE TITLE
Configure renovate to update all dependencies in docker file at once

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/deploy-sourcegraph#108]
Farhan wanted to release 2.12 so he created this PR:
https://github.com/sourcegraph/deploy-sourcegraph/pull/105

There are two practical problems with renovate:
1. It is unclear when it will detect the update and
2. In this case it only updated two of the dependencies, but they need to be updated together
    - https://github.com/sourcegraph/deploy-sourcegraph/pull/106
    - https://github.com/sourcegraph/deploy-sourcegraph/pull/107

@felixfbecker do you have advice on how to configure Renovate better here to get what we want?

**Comment by felixfbecker** [comment]
Here's how we group OSS webapp+backend updates to enterprise:

https://github.com/sourcegraph/enterprise/blob/ef085c80de4257dda9c4a2d18715077806040de4/renovate.json#L7-L8

Not sure what exactly is desired but `"packagePattern": "^sourcegraph/"` would group all `sourcegraph/` images.

> It is unclear when it will detect the update and in this case it only updated two of the dependencies

When in doubt you can check https://renovatebot.com/dashboard#gh/sourcegraph/deploy-sourcegraph
I don't know why it only detected two updates (I see 4 PRs?), but the logs might give it away. Reasons can be: CI still pending, caching, PR limit hit, schedule, ...

**Comment by felixfbecker** [comment]
I see this in the logs:

```
Reached PR creation limit - skipping branch creation
```

**Comment by felixfbecker** [comment]
The default for `config:base`, which renovate.json extends, is `prHourlyCreation: 2`, which means at most 2 PRs get created per hour. Grouping everything into one PR would therefor also solve this issue, but you may want to consider increasing this.

**Comment by nicksnyder** [comment]
Thanks for the help! I merged the PR so this should be fixed.
