### ISSUE TITLE
Publish seperate zoekt 'indexserver' and 'webserver' images with more defaults baked in

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/deploy-sourcegraph#127]
Today, users must specify a ton of arguments to our `sourcegraph/zoekt` image to run the indexserver and webserver:

https://github.com/sourcegraph/deploy-sourcegraph/blob/bd53e169b5c0405ad4db1114c780cb5cdc729a2c/base/indexed-search/indexed-search.Deployment.yaml#L55-L68

https://github.com/sourcegraph/deploy-sourcegraph/blob/bd53e169b5c0405ad4db1114c780cb5cdc729a2c/base/indexed-search/indexed-search.Deployment.yaml#L27-L34

It would be much better from a pure-Docker deployment perspective to publish separate `sourcegraph/zoekt-indexserver` and `sourcegraph/zoekt-webserver` Docker images with many of these defaults baked in. i.e. only `-sourcegraph_url` should be required for indexserver, and nothing required for webserver.

**Comment by keegancsmith** [comment]
Note that both of these images need to share a volume (`/data/index`). We can bake in these defaults and make it different images. I'm interested to hear your motivation for that though.

**Comment by slimsag** [comment]
Oh, nice, I didn't know that. Thanks! That saves me from tracking down a bug :)

My motivation is simple: I'm trying to make a [pure-Docker cluster deployment option](https://github.com/sourcegraph/deploy-sourcegraph-docker) and any extra args etc. that we need to specify make our deployment config that much more complex.
