### ISSUE TITLE
gitserver running as user 0

### ISSUE THREAD

**Issue by CH-JosephBironas** [sourcegraph/deploy-sourcegraph#206]
More a question than an issue, but one with security implications.

Why is the gitserver statefulset using: `runAsUser: 0`?

Doing a quick experiment, I get this log line:
2019/02/28 03:08:46 failed to setup temporary directory: mkdir /data/repos/.tmp-old600362932: permission denied

It's possible this is an instantiation error though as it was an existing volume mounted inside an existing statefulset.

**Comment by slimsag** [comment]
Related (but not the same): https://github.com/sourcegraph/sourcegraph/issues/2044

_There is no good reason for us to be running containers as root._

It is something we need to address, but will require some additional work in terms of migrating existing users (as all the data is owned by root, too). To quote @beyang from a Slack thread:

> 1. The docker images originally all ran as root user.
> 2. We changed some of the docker images to *not* require root user
> 3. However, migrating old disks attached to existing deployments had a bunch of root-owned files. It would have been more work to migrate these over to be non-root owned (the idea I had at the time was to attach a sidecar container that chown'd the directories to the non-root user, but this would've taken more time).
> 4. So we made running as root user as the default.

---

> 2019/02/28 03:08:46 failed to setup temporary directory: mkdir /data/repos/.tmp-old600362932: permission denied

Can you clarify what you did to get this error? If deploying sourcegraph, you definitely should not be seeing this.

**Comment by terinjokes** [comment]
If we're spinning up a new deployment, is this something we can change, or should we hold off for now?

> the idea I had at the time was to attach a sidecar container that chown'd the directories to the non-root user, but this would've taken more time

This sounds like a job for an init container.

**Comment by slimsag** [comment]
I'd suggest holding off for now, until we have something in place to handle the migration needed here. (this way at least your deployment is consistent with the rest)

**Comment by CH-JosephBironas** [comment]
Sorry for the long delay -- there was some amount of time where the future of our use of sourcegraph was in jeopardy. Fortunately we're past that now. I assume the service was creating a directory and couldn't due to lack of permissions, or lack of alignment between users and permissions. It's not clear if a `runAsUser` directive with specific permissions would have fixed the issue.

**Comment by zoidbergwill** [comment]
We run as a non-root user, and it works.

Using `runAsUser:` is necessary so, between pod / container restarts, the running user still has access to the files/directories, if you have persistent storage.

**Comment by beyang** [comment]
As of 3.14, all Sourcegraph services no longer run as root by default.
