### ISSUE TITLE
Update svc/sourcegraph-frontend to use port 3080?

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/deploy-sourcegraph#267]
https://github.com/sourcegraph/deploy-sourcegraph/blob/bf90e1d0f6356dbc75fddd9f8fb67af3a4f8b565/base/frontend/sourcegraph-frontend.Service.yaml#L14

This would be consistent with our other products. I believe we used 30080 back in the day due to using a nodeport? Would updating the port have any downsides?

**Comment by beyang** [comment]
wontfix
