### ISSUE TITLE
Updating image tags is error-prone and tedious

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/deploy-sourcegraph#287]
When cutting a new release, the image tags in the YAML here must be updated which is error-prone and tedious work.

In the best case, Renovate creates the appropriate PR and you just merge + cherry pick it onto e.g. the `3.5` branch and tag the release. However:

1. Renovate does not always include the relevant tags in the update if it doesn't have time to discover them. When I merged https://github.com/sourcegraph/deploy-sourcegraph/pull/278 all images were released and on Docker Hub, but it did not update the `frontend` tag and I missed this which caused the 3.5.1 release to incorrectly not bump the frontend version. The only way I could have caught this was by clicking `rebase` and waiting for it to rebase OR by manually comparing the list of updated images against all that should be updated.

2. When the versions are incorrect, as was the case after I merged https://github.com/sourcegraph/deploy-sourcegraph/pull/278 -- Renovate created this PR which upgraded the version from 3.5.0 -> 3.5.1 *instead of* to 3.5.2 as I expected. https://github.com/sourcegraph/deploy-sourcegraph/pull/282

The TL;DR here seems to be that I should not trust the PRs renovate creates and need to actually review them -- despite the fact that they are machine generated.

Proposal: Can we just have a `VERSION=3.5.2 ./update-image-tags.sh` script instead? This would be much faster than Renovate and would give me more confidence in the change.

**Comment by slimsag** [comment]
This just happened again. Luckily not an actual issue this time around, though. https://sourcegraph.slack.com/archives/C0EPTDE9L/p1566521183091600?thread_ts=1566501269.087000&cid=C0EPTDE9L

**Comment by beyang** [comment]
Migrated to https://github.com/sourcegraph/sourcegraph/issues/9725
