### ISSUE TITLE
Remove generated code in examples/ and test-cases/ from this repo

### ISSUE THREAD

**Issue by sqs** [sourcegraph/deploy-sourcegraph#34]
Each time you change image tags in values.yaml, the diff changes 76 other files (in `examples/` and `test-cases/`). This makes it noisy to review diffs.

I understand there is value to seeing the actual effects of changes to values.yaml on real-world configs, but I personally find that it creates more noise than it helps.

Proposal: Only have the example/test-case values.yaml files in this repo, not the entire set of generated yaml files derived from them.

**Comment by keegancsmith** [comment]
Agreed. However, I think there is value from a CI perspective to still generate and run kubeval on the output. It can catch many bugs. Just don't commit the output.

**Comment by beyang** [comment]
Having a way to quickly verify test output changed in an expected way has been extremely useful to me. What would replace that if we were to remove the generated files from this repository? Are the linguist-generated rules insufficient in denoising diffs?

**Comment by beyang** [comment]
> I personally always create PRs with the generate commit separate to simplify reviewing.

This is what I do, as well. I'm fine with instituting this policy.
