### ISSUE TITLE
function "nindent" not defined

### ISSUE THREAD

**Issue by prestonvanloon** [sourcegraph/deploy-sourcegraph#37]
Error: parse error in "sourcegraph/templates/xlang/typescript/xlang-typescript.Deployment.yaml": template: sourcegraph/templates/xlang/typescript/xlang-typescript.Deployment.yaml:41: function "nindent" not defined

Just following the instructions here: https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/install.md

**Comment by prestonvanloon** [comment]
Ah, yes. Maybe I wasn't following the instructions correctly :)

```
helm version
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```

It was indeed the helm install part. 

Upgrading the helm client and server to 2.9.1 seems to have resolved the issue!

**Comment by beyang** [comment]
Awesome. Let us know if you run into any further issues!
