### ISSUE TITLE
Grafana persistent volume size

### ISSUE THREAD

**Issue by aisbaa** [sourcegraph/deploy-sourcegraph#387]
Hi, I'm just curious why grafana persistent volume is so big 200Gi, which is the same size as prometheus. To my understanding grafana does not store time series data on disk, it only needs to store dashboards and datasource configuration, sometimes user passwords. None of these should required a lot of space, but maybe I'm missing something.

Here's the file https://github.com/sourcegraph/deploy-sourcegraph/blob/master/base/grafana/grafana.PersistentVolumeClaim.yaml

Some examples online provide dashboard configuration in ConfigMap and do not assign any persistent volume to grafana pod. I think sharing dashboard configuration in ConfigMap is One of the best ways to do that!

**Comment by beyang** [comment]
@aisbaa you are absolutely right (and sorry about the delay here; we are migrating issues in this repository to the Sourcegraph main issue tracker to better keep track of them). Feel free to reduce the disk size. We'll also update this in our next version.

**Comment by aisbaa** [comment]
Thats so cool, thank you.
