### ISSUE TITLE
gitserver low disk alert using hardcoded threshold

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/deploy-sourcegraph#456]
find a way to keep in sync with SRC_REPOS_DESIRED_PERCENT_FREE:

https://github.com/sourcegraph/sourcegraph/blob/7da2f8d8a3851083090d7c6bf4d3d3dc35745697/cmd/gitserver/main.go#L30

**Comment by beyang** [comment]
@uwedeportivo if this is still an issue can you re-file in github.com/sourcegraph/sourcegraph?
