### ISSUE TITLE
Enforce pod security policies

### ISSUE THREAD

**Issue by beyang** [sourcegraph/deploy-sourcegraph#482]
See [RFC 103](https://docs.google.com/document/d/1TrF_5JNAu0ran0VKymeifiKMKRu6p3OFBesWWKZ7yAE/edit#) for details.

**Comment by slimsag** [comment]
Be careful that these changes do not result in existing clusters having file permission issues. You could use a container init script to migrate existing clusters potentially

**Comment by uwedeportivo** [comment]
i'm going to keep notes here as i make progress.

https://github.com/sourcegraph/about/pull/534

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/deploy-sourcegraph/pull/513

for goal one, i think i know what's going on. i'm testing a fix

**Comment by uwedeportivo** [comment]
https://github.com/kubernetes/kubernetes/issues/2630

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/deploy-sourcegraph/tree/namespaced-sourcegraph has all the restrictions from RFC 103 implemented. for new installations this will work. next up is migration of existing installations.

https://sourcegraph.com/github.com/sourcegraph/about/-/blob/handbook/engineering/distribution/k8s_admin_custom_policy.md?utm_product_name=GoLand&utm_product_version=GoLand#L1:55
explains how to simulate being an admin with restrictions installing Sourcegraph

**Comment by beyang** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/9603
