### ISSUE TITLE
SSD cache permissions

### ISSUE THREAD

**Issue by efritz** [sourcegraph/deploy-sourcegraph#572]
After running the nonroot overlay on DotCom, we found that the frontend pods (among others) that amount a cache directory in a shared SSH do not have the correct permissions for writing.

https://github.com/sourcegraph/deploy-sourcegraph/tree/master/configure/ssd

These services mount the SSD cache:

- sourcegraph-frontend
- searcher
- symbols
- lang-go
- lang-typescript
- pod-tmp-gc

**Comment by efritz** [comment]
This was resolved on DotCom via

```
gcloud compute instances list | grep dot-com
```

and

```
gcloud compute ssh gke-dot-com-dot-com-{node-id} --command 'sudo chmod -R 0777 /mnt/disks/ssd0/pod-tmp'
```

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/deploy-sourcegraph/pull/583 fixes this
