### ISSUE TITLE
Split the manifests for non-admin users

### ISSUE THREAD

**Issue by dadux** [sourcegraph/deploy-sourcegraph#596]
We run large multi-tenanted Kubernetes clusters, with a dedicated team looking after the cluster (admin, monitoring, etc...)
All the clusters are self-service as much as possible.

One of our a team have successfully deployed sourcegraph in their own namespace, but in order to do so they had to manually apply only a subset of the manifests. 
Some objects (ClusterRoleBindings for example) require cluster-admin privileges. 

Would it be possible to split the config for non-admin users when doing the `kubectl-apply-all.sh` ? I believe only the prometheus config requires cluster wide privileges, and we already manage that in a separate instance.

This would greatly make upgrades easier for them if they can use the upstream tool.

**Comment by beyang** [comment]
Closing down this issue tracker, migrated issue to https://github.com/sourcegraph/sourcegraph/issues/9723
